{"errorMessage": "The adapter was unable to infer a handler to use for the event. This is likely related to how the Lambda function was invoked. (Are you testing locally? Make sure the request payload is valid for a supported handler.)", "errorType": "RuntimeError", "requestId": "5ae37970-7bef-4ee9-a57c-b143e22dce5f", "stackTrace": ["  File \"/var/task/gmail_server.py\", line 355, in lambda_handler\n    return handler(event, context)\n", "  File \"/var/lang/lib/python3.11/site-packages/mangum/adapter.py\", line 76, in __call__\n    handler = self.infer(event, context)\n", "  File \"/var/lang/lib/python3.11/site-packages/mangum/adapter.py\", line 68, in infer\n    raise RuntimeError(  # pragma: no cover\n"]}